[project]
name = "csv-analyzer-mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.9.1",
    "pandas>=2.2.3",
    "rich>=14.0.0",
]
